"use client";

import { useEffect, useState, Suspense } from "react";
import { useSearchParams } from "next/navigation";
import { format } from "date-fns";
import { Printer, Download, Loader2 } from "lucide-react";

interface ReportData {
  entityName: string;
  isFirm: boolean;
  period: string;
  startDate: string;
  endDate: string;
  totalTransactions: number;
  totalAmount: number;
  totalTax: number;
  statusSummary: Record<string, number>;
  companyBreakdown: Array<{ name: string; count: number; amount: number; topVendors: string[] }>;
  typeBreakdown: Array<{ type: string; count: number; amount: number }>;
  transactions: Array<{
    id: string;
    vendorName?: string;
    invoiceNumber?: string;
    invoiceDate?: string;
    totalAmount?: number;
    taxAmount?: number;
    acceptedAt?: string;
    company: string;
    documentType: string;
  }>;
}

const PERIOD_LABELS: Record<string, string> = {
  last7: "Last 7 Days",
  last30: "Last 30 Days",
  last90: "Last 90 Days",
  all: "All Time",
};

const TYPE_LABELS: Record<string, string> = {
  INVOICE: "Invoice",
  RECEIPT: "Receipt",
  BANK_STATEMENT: "Bank Statement",
  SALARY_REGISTER: "Salary Register",
  LEDGER: "Ledger",
  OTHER: "Other",
};

function formatINR(amount: number) {
  return `₹${amount.toLocaleString("en-IN", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

export default function GenerateReportPage() {
  return (
    <Suspense>
      <GenerateReportInner />
    </Suspense>
  );
}

function GenerateReportInner() {
  const searchParams = useSearchParams();
  const period = searchParams.get("period") || "last30";
  const [data, setData] = useState<ReportData | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch(`/api/reports/generate?period=${period}`)
      .then((r) => r.json())
      .then((d) => { setData(d); setLoading(false); })
      .catch(() => setLoading(false));
  }, [period]);

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-white">
        <div className="flex items-center gap-3 text-gray-500">
          <Loader2 className="w-5 h-5 animate-spin" />
          <span>Generating report...</span>
        </div>
      </div>
    );
  }

  if (!data) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-white">
        <p className="text-gray-500">Failed to generate report.</p>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-white">
      {/* Print toolbar */}
      <div className="print:hidden sticky top-0 z-50 bg-white border-b border-gray-200 px-6 py-3 flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-indigo-500 to-violet-600 flex items-center justify-center">
            <span className="text-white text-xs font-bold">F</span>
          </div>
          <span className="font-bold text-sm text-gray-900">FinBridge Report</span>
        </div>
        <div className="flex items-center gap-2">
          <button
            onClick={() => window.print()}
            className="flex items-center gap-2 px-4 py-2 bg-indigo-600 text-white text-sm font-medium rounded-lg hover:bg-indigo-700 transition-colors"
          >
            <Printer className="w-4 h-4" />
            Print / Save as PDF
          </button>
          <button
            onClick={() => window.close()}
            className="px-4 py-2 text-sm font-medium text-gray-600 hover:text-gray-900 transition-colors"
          >
            Close
          </button>
        </div>
      </div>

      {/* Report content */}
      <div className="max-w-4xl mx-auto px-8 py-10 print:px-0 print:py-0 print:max-w-none">
        {/* Header */}
        <div className="border-b-2 border-indigo-600 pb-6 mb-8">
          <div className="flex items-start justify-between">
            <div>
              <h1 className="text-2xl font-bold text-gray-900">Financial Report</h1>
              <p className="text-lg text-indigo-600 font-semibold mt-1">{data.entityName}</p>
            </div>
            <div className="text-right">
              <div className="w-10 h-10 rounded-lg bg-gradient-to-br from-indigo-500 to-violet-600 flex items-center justify-center ml-auto mb-2">
                <span className="text-white text-sm font-bold">FB</span>
              </div>
              <p className="text-xs text-gray-500">Generated by FinBridge</p>
            </div>
          </div>
          <div className="flex items-center gap-6 mt-4 text-sm text-gray-600">
            <span><strong>Period:</strong> {PERIOD_LABELS[data.period] || data.period}</span>
            <span><strong>From:</strong> {format(new Date(data.startDate), "MMM d, yyyy")}</span>
            <span><strong>To:</strong> {format(new Date(data.endDate), "MMM d, yyyy")}</span>
            <span><strong>Generated:</strong> {format(new Date(), "MMM d, yyyy h:mm a")}</span>
          </div>
        </div>

        {/* Executive Summary */}
        <section className="mb-8 break-inside-avoid">
          <h2 className="text-lg font-bold text-gray-900 mb-4 flex items-center gap-2">
            <span className="w-1 h-5 bg-indigo-600 rounded-full" />
            Executive Summary
          </h2>
          <div className="grid grid-cols-4 gap-4">
            {[
              { label: "Total Transactions", value: data.totalTransactions.toString() },
              { label: "Total Amount", value: formatINR(data.totalAmount) },
              { label: "Total Tax", value: formatINR(data.totalTax) },
              { label: "Net Amount", value: formatINR(data.totalAmount - data.totalTax) },
            ].map((item) => (
              <div key={item.label} className="bg-gray-50 rounded-lg p-4 border border-gray-200">
                <p className="text-xs text-gray-500 uppercase tracking-wider">{item.label}</p>
                <p className="text-lg font-bold text-gray-900 mt-1">{item.value}</p>
              </div>
            ))}
          </div>
        </section>

        {/* Status Summary */}
        <section className="mb-8 break-inside-avoid">
          <h2 className="text-lg font-bold text-gray-900 mb-4 flex items-center gap-2">
            <span className="w-1 h-5 bg-indigo-600 rounded-full" />
            Transaction Status Overview
          </h2>
          <div className="flex gap-3">
            {Object.entries(data.statusSummary).map(([status, count]) => {
              const colors: Record<string, string> = {
                ACCEPTED: "bg-emerald-50 border-emerald-200 text-emerald-700",
                PENDING: "bg-amber-50 border-amber-200 text-amber-700",
                UNDER_REVIEW: "bg-blue-50 border-blue-200 text-blue-700",
                REJECTED: "bg-red-50 border-red-200 text-red-700",
                NEEDS_INFO: "bg-orange-50 border-orange-200 text-orange-700",
              };
              return (
                <div key={status} className={`flex-1 rounded-lg p-3 border ${colors[status] ?? "bg-gray-50 border-gray-200 text-gray-700"}`}>
                  <p className="text-xs font-medium">{status.replace(/_/g, " ")}</p>
                  <p className="text-xl font-bold mt-0.5">{count}</p>
                </div>
              );
            })}
          </div>
        </section>

        {/* Company Breakdown */}
        {data.companyBreakdown.length > 0 && (
          <section className="mb-8 break-inside-avoid">
            <h2 className="text-lg font-bold text-gray-900 mb-4 flex items-center gap-2">
              <span className="w-1 h-5 bg-indigo-600 rounded-full" />
              Breakdown by Company
            </h2>
            <table className="w-full border-collapse">
              <thead>
                <tr className="bg-indigo-50">
                  <th className="text-left text-xs font-semibold text-indigo-900 uppercase tracking-wider px-4 py-2.5 border border-indigo-100">Company</th>
                  <th className="text-right text-xs font-semibold text-indigo-900 uppercase tracking-wider px-4 py-2.5 border border-indigo-100">Transactions</th>
                  <th className="text-right text-xs font-semibold text-indigo-900 uppercase tracking-wider px-4 py-2.5 border border-indigo-100">Total Amount</th>
                  <th className="text-left text-xs font-semibold text-indigo-900 uppercase tracking-wider px-4 py-2.5 border border-indigo-100">Top Vendors</th>
                </tr>
              </thead>
              <tbody>
                {data.companyBreakdown.map((company, i) => (
                  <tr key={company.name} className={i % 2 === 0 ? "bg-white" : "bg-gray-50"}>
                    <td className="px-4 py-2.5 text-sm font-medium text-gray-900 border border-gray-200">{company.name}</td>
                    <td className="px-4 py-2.5 text-sm text-gray-700 text-right tabular-nums border border-gray-200">{company.count}</td>
                    <td className="px-4 py-2.5 text-sm font-semibold text-gray-900 text-right tabular-nums border border-gray-200">{formatINR(company.amount)}</td>
                    <td className="px-4 py-2.5 text-xs text-gray-500 border border-gray-200">{company.topVendors.join(", ") || "—"}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </section>
        )}

        {/* Document Type Breakdown */}
        <section className="mb-8 break-inside-avoid">
          <h2 className="text-lg font-bold text-gray-900 mb-4 flex items-center gap-2">
            <span className="w-1 h-5 bg-indigo-600 rounded-full" />
            Breakdown by Document Type
          </h2>
          <div className="grid grid-cols-3 gap-3">
            {data.typeBreakdown.map((type) => (
              <div key={type.type} className="bg-gray-50 rounded-lg p-4 border border-gray-200">
                <p className="text-xs text-gray-500 font-medium">{TYPE_LABELS[type.type] ?? type.type}</p>
                <p className="text-lg font-bold text-gray-900">{type.count}</p>
                <p className="text-sm text-indigo-600 font-semibold">{formatINR(type.amount)}</p>
              </div>
            ))}
          </div>
        </section>

        {/* Transaction Detail Table */}
        <section className="mb-8">
          <h2 className="text-lg font-bold text-gray-900 mb-4 flex items-center gap-2">
            <span className="w-1 h-5 bg-indigo-600 rounded-full" />
            Accepted Transactions Detail
          </h2>
          <table className="w-full border-collapse text-xs">
            <thead>
              <tr className="bg-indigo-50">
                {["#", "Vendor", "Invoice #", "Company", "Type", "Date", "Tax", "Total"].map((h) => (
                  <th key={h} className="text-left font-semibold text-indigo-900 uppercase tracking-wider px-3 py-2 border border-indigo-100">
                    {h}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {data.transactions.map((tx, i) => (
                <tr key={tx.id} className={i % 2 === 0 ? "bg-white" : "bg-gray-50"}>
                  <td className="px-3 py-2 text-gray-500 border border-gray-200">{i + 1}</td>
                  <td className="px-3 py-2 font-medium text-gray-900 border border-gray-200">{tx.vendorName || "—"}</td>
                  <td className="px-3 py-2 text-gray-600 border border-gray-200">{tx.invoiceNumber || "—"}</td>
                  <td className="px-3 py-2 text-gray-600 border border-gray-200">{tx.company}</td>
                  <td className="px-3 py-2 text-gray-600 border border-gray-200">{TYPE_LABELS[tx.documentType] ?? tx.documentType}</td>
                  <td className="px-3 py-2 text-gray-600 tabular-nums border border-gray-200">
                    {tx.invoiceDate ? format(new Date(tx.invoiceDate), "MMM d, yy") : "—"}
                  </td>
                  <td className="px-3 py-2 text-gray-600 tabular-nums text-right border border-gray-200">
                    {tx.taxAmount ? formatINR(tx.taxAmount) : "—"}
                  </td>
                  <td className="px-3 py-2 font-semibold text-gray-900 tabular-nums text-right border border-gray-200">
                    {tx.totalAmount ? formatINR(tx.totalAmount) : "—"}
                  </td>
                </tr>
              ))}
            </tbody>
            <tfoot>
              <tr className="bg-indigo-50 font-bold">
                <td colSpan={6} className="px-3 py-2.5 text-indigo-900 border border-indigo-100">Grand Total</td>
                <td className="px-3 py-2.5 text-indigo-900 text-right tabular-nums border border-indigo-100">{formatINR(data.totalTax)}</td>
                <td className="px-3 py-2.5 text-indigo-900 text-right tabular-nums border border-indigo-100">{formatINR(data.totalAmount)}</td>
              </tr>
            </tfoot>
          </table>
        </section>

        {/* Footer */}
        <div className="border-t-2 border-indigo-600 pt-4 mt-12 text-center">
          <p className="text-xs text-gray-400">
            Generated by FinBridge &bull; {data.entityName} &bull; {format(new Date(), "MMMM d, yyyy h:mm a")} &bull; Confidential
          </p>
        </div>
      </div>
    </div>
  );
}
